### ISSUE TITLE
1.12.2 issue

### ISSUE THREAD

**Issue by rubenh2905** [Tfarcenim/ModdingSkeletonMixin#2]
http links are not working anymore, just https

```
Error downloading asset (try 2) : minecraft/lang/ar_sa.lang
java.io.IOException: Server returned HTTP response code: 400 for URL: http://resources.download.minecraft.net/9e/9e0d4e96d478589bdfa21302ecbcb58bc2069e7a
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1902)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500)
        at java.net.URL.openStream(URL.java:1093)
        at net.minecraftforge.gradle.tasks.DownloadAssetsTask$GetAssetTask.call(DownloadAssetsTask.java:189)
        at net.minecraftforge.gradle.tasks.DownloadAssetsTask$GetAssetTask.call(DownloadAssetsTask.java:150)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

**Comment by Tfarcenim** [comment]
Killed the unneeded http links
